option('gdk-pixbuf', type: 'feature', value: 'auto', description: 'Enable support for more image formats')
option('libnotify', type: 'feature', value: 'auto', description: 'Enable support for desktop notifications')
option('man-pages', type: 'feature', value: 'auto', description: 'Generate and install man pages')
